# -*- coding: utf-8 -*-
"""Proyecto_transacciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQswiBqDR-xxTJynEO22qtWneiUY0vH0

1. Instalacion de libreria que seran usadas en el desarrollo
"""

import pandas as pd
import numpy as np
import json
!pip install pyarrow

"""2. Carga del archivo Json"""

records = []

with open('/content/transactions_50k.jsonl', 'r') as f:
    for line in f:
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            continue

df = pd.DataFrame(records)
df.head(5)

# Campos obligatorios
required_fields = ['created_at', 'status', 'amount_in_cents']
df = df.dropna(subset=required_fields)

# Validar tipo de fecha
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
df = df.dropna(subset=['created_at'])

# Validar montos
df['amount_in_cents'] = pd.to_numeric(df['amount_in_cents'], errors='coerce')
df = df[df['amount_in_cents'] > 0]

# Validar status esperado
df = df[df['status'].isin(['APPROVED', 'DECLINED'])]

"""3. Identificacion de campos requeridos

3.1. BIN → viene dentro del campo anidado payment_method_type → extra → bin
"""

df['bin'] = df['payment_method_type'].apply(lambda x: x.get('extra', {}).get('bin'))
df['bin'].head(5)

"""3.2. Día de la transacción → viene en created_at

"""

df['date'] = pd.to_datetime(df['created_at']).dt.date
df['date'].head(5)

"""3.3 Cantidad de transacciones aprobadas"""

df_approved = df[df['status'] == 'APPROVED']
df_approved.head(5)

"""3.4. Monto total aprobado"""

summary = df_approved.groupby(['bin', 'date']).agg(
    approved_transactions=('id', 'count'),
    total_approved_amount=('amount_in_cents', 'sum')
).reset_index()

summary.head(5)

"""4.Vista final"""

summary.to_parquet('/content/summary_transactions.parquet', index=False)

summary.head()